config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show] do
    resources :conversations, only:[:index, :show, :create]
  end
  resource :session, only:[:create, :destroy]
  resources :users, only: [:new, :create]
  get 'login' => 'sessions#new'
  get 'logout'=> 'sessions#destroy'
  root 'topics#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :topic, touch: true
  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :messages
  validates :name, presence: true, length:{minimum:10}
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation, touch: true
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :category
  has_many :conversations

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def conversations_most_recent_first
    conversations.order(updated_at: :desc)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :messages
  has_many :conversations
  validates_presence_of :email, :username

  def username_in_lower_case
    return nil unless username
    username.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  before_action :ensure_logged_in

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def ensure_logged_in
    redirect_to login_path unless current_user
  end



end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @topic = Topic.find(params[:topic_id])
    @conv  = Conversation.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @conv = @topic.conversations.build(conv_params)
    if @conv.save
      redirect_to topic_conversations_path(@topic)
    else
      render :index
    end
  end

  private 
  def conv_params
     params.require(:conversation).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_logged_in

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      flash[:notice] = 'Welcome to our site'
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:warning] = 'Login failed'
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = 'Bye'
    redirect_to root_path
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :ensure_logged_in, only:[:index, :show]

  def index
    @topics = Topic.order(updated_at: :desc)
  end

  def show
    topic = Topic.find(params[:id])
    redirect_to topic_conversations_path(topic)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Thanks for registering'
      redirect_to root_path
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(d)
    return "" unless d
    d.strftime('%b %e %l:%M %p')
  end
end

app/views/conversations/_conversation.html.erb
<li>
<%= conversation.name %> (<%= format_date(conversation.updated_at) %>)
</li>

app/views/conversations/index.html.erb
<h1>Conversations in <%= @topic.name %> </h1>
<ul>
  <%= render @topic.conversations_most_recent_first %>
</ul>

<% if @conv.errors.any? %>
   <%= @conv.errors.full_messages %>
<% end %>

<%= form_for [@topic, @conv] do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RBulletin</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="flash-container">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>
</div>

<div>
  <% if current_user %>
    Welcome <%= current_user.username %>
    <%= link_to 'Log out', logout_path %>
  <% else %>
    Please <%= link_to 'Login', login_path %> or 
    <%= link_to 'Register', new_user_path %>
  <% end %>
</div>


<%= yield %>

</body>
</html>

app/views/topics/_topic.html.erb
<tr class="topic">
  <td data-topic-id="<%= topic.id %>" data-topic-name="<%= topic.name %>"  data-topic-category="<%= topic.category.id %>" class="topic-name"><%= link_to topic.name, topic_path(topic) %></td>
  <td class="topic-updated"><%= format_date(topic.updated_at) %></td>
</tr>

app/views/topics/index.html.erb
<h1>Topics</h1>
<table data-purpose="topic-list">
  <tr>
    <th>Topic Name</th>
    <th>Last message at</th>
  </tr>

<%= render @topics %>

</table>

app/views/users/new.html.erb
<div>
<%= @user.errors.full_messages %>
</div>

<%= form_for @user do |f| %>
<div>
 <%= f.label :username %>
 <%= f.text_field :username %>
</div>
<div>
 <%= f.label :email %>
 <%= f.text_field :email %>
</div>
<div>

 <%= f.label :password %>
 <%= f.password_field :password %>
</div>
<div>

 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation %>
</div>
<div>

 <%= f.submit %>
</div>


<% end %>